#!/bin/sh
# Start/stop the tuer daemon core.
#
### BEGIN INIT INFO
# Provides:          tuer_core
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

EXE_DOOR=/flash/tuer/door_daemon_zmq
DOOR_DEV=/dev/door

. /etc/default/tuer

PIDFILE_DOOR=${DIR_RUN}/door_daemon.pid

test -e $EXE_DOOR  || exit 1
if [ ! -d $DIR_RUN ]; then
	mkdir -p $DIR_RUN || exit 2
	chown -R $DOOR_USR:$DOOR_GRP $DIR_RUN
fi
chown $DOOR_USR:$DOOR_GRP $DOOR_DEV

. /lib/lsb/init-functions

# Read the system's locale and set cron's locale. This locale
# will be inherited by cron (used to set charset of emails)
# and tasks running under it.

case "$1" in
start)
  log_daemon_msg "Starting door daemon" "door_daemon_zmq"
  start-stop-daemon --start --quiet --pidfile $PIDFILE_DOOR -c $DOOR_USR -m -g $DOOR_GRP -b --name door_daemon_zmq --startas $EXE_DOOR -- --device $DOOR_DEV --cmdport "$DOOR_SOCKET" --syslog
  log_end_msg $?
  ;;
stop)
  log_daemon_msg "Stopping door daemon" "door_daemon_zmq"
  start-stop-daemon --stop --quiet --pidfile $PIDFILE_DOOR -m --name door_daemon_zmq
  log_end_msg $?
        ;;
restart)
	$0 stop
	$0 start
        ;;
*)	log_action_msg "Usage: $0 {start|stop|restart|reload|force-reload}"
        exit 2
        ;;
esac
exit 0
