#!/bin/sh
# Start/stop the tuer status updater.
#
### BEGIN INIT INFO
# Provides:          tuer_presence
# Required-Start:    $remote_fs $syslog $time tuer_core
# Required-Stop:     $remote_fs $syslog $time tuer_core
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

EXE_TRACK=/flash/tuer/r3-eventbroker_zmq
CFG_TRACK="--syslog"

. /etc/default/tuer

[ -n "$DEBUG" ] && CFG_TRACK="$CFG_TRACK --debug"

PIDFILE_TRACK=${DIR_RUN}/r3-eventbroker_zmq.pid
test -f $EXE_TRACK  || exit 1
if [ ! -d $DIR_RUN ]; then
	mkdir -p $DIR_RUN || exit 2
	chown -R $DOOR_USR:$DOOR_GRP $DIR_RUN
fi

. /lib/lsb/init-functions

# Read the system's locale and set cron's locale. This locale
# will be inherited by cron (used to set charset of emails)
# and tasks running under it.

case "$1" in
start)	
	log_daemon_msg "Starting r3 event broker" "r3-eventbroker_zmq"
        start-stop-daemon --start --quiet --pidfile $PIDFILE_TRACK -b -m -c $DOOR_USR -g $DOOR_GRP --startas $EXE_TRACK  -- $CFG_TRACK
        log_end_msg $?	
	;;
stop)
	log_daemon_msg "Stopping r3 event broker" "r3-eventbroker_zmq"
        start-stop-daemon --stop --quiet --pidfile $PIDFILE_TRACK -m --retry TERM/1/TERM/1/KILL 
        log_end_msg $?	
        ;;
restart) 
	$0 stop
	$0 start
        ;;
*)	log_action_msg "Usage: $0 {start|stop|restart|reload|force-reload}"
        exit 2
        ;;
esac
exit 0
