// (c) Bernhard Tittelbach, 2015

package r3events

const (
	TOPIC_R3                     string = "realraum/"
	TOPIC_ACTIONS                string = "action/"
	CLIENTID_FRONTDOOR           string = "frontdoor"
	CLIENTID_BACKDOOR            string = "backdoorcx"
	CLIENTID_PILLAR              string = "pillar"
	CLIENTID_OLGAFREEZER         string = "olgafreezer"
	CLIENTID_META                string = "metaevt"
	CLIENTID_GW                  string = "gateway"
	CLIENTID_LASERCUTTER         string = "lasercutter"
	CLIENTID_XMPPBOT             string = "xmppbot"
	ACTDESTID_RF433              string = "rf433"
	ACTDESTID_YAMAHA             string = "yamahastereo"
	TOPIC_FRONTDOOR_LOCK         string = TOPIC_R3 + CLIENTID_FRONTDOOR + "/lock"
	TOPIC_FRONTDOOR_AJAR         string = TOPIC_R3 + CLIENTID_FRONTDOOR + "/ajar"
	TOPIC_FRONTDOOR_CMDEVT       string = TOPIC_R3 + CLIENTID_FRONTDOOR + "/cmdevt"
	TOPIC_FRONTDOOR_PROBLEM      string = TOPIC_R3 + CLIENTID_FRONTDOOR + "/problemevt"
	TOPIC_FRONTDOOR_MANUALLOCK   string = TOPIC_R3 + CLIENTID_FRONTDOOR + "/manuallockmovement"
	TOPIC_FRONTDOOR_RAWFWLINES   string = TOPIC_R3 + CLIENTID_FRONTDOOR + "/rawfwlines"
	TOPIC_PILLAR_DOOMBUTTON      string = TOPIC_R3 + CLIENTID_PILLAR + "/boredoombuttonpressed"
	TOPIC_PILLAR_TEMP            string = TOPIC_R3 + CLIENTID_PILLAR + "/temperature"
	TOPIC_PILLAR_ILLUMINATION    string = TOPIC_R3 + CLIENTID_PILLAR + "/illumination"
	TOPIC_PILLAR_DUST            string = TOPIC_R3 + CLIENTID_PILLAR + "/dust"
	TOPIC_PILLAR_RELHUMIDITY     string = TOPIC_R3 + CLIENTID_PILLAR + "/relhumidity"
	TOPIC_PILLAR_MOVEMENTPIR     string = TOPIC_R3 + CLIENTID_PILLAR + "/movement"
	TOPIC_BACKDOOR_MOVEMENTPIR   string = TOPIC_R3 + CLIENTID_BACKDOOR + "/movement"
	TOPIC_OLGAFREEZER_TEMP       string = TOPIC_R3 + CLIENTID_OLGAFREEZER + "/temperature"
	TOPIC_OLGAFREEZER_TEMPOVER   string = TOPIC_R3 + CLIENTID_OLGAFREEZER + "/overtemp"
	TOPIC_OLGAFREEZER_SENSORLOST string = TOPIC_R3 + CLIENTID_OLGAFREEZER + "/sensorlost"
	TOPIC_BACKDOOR_TEMP          string = TOPIC_R3 + CLIENTID_BACKDOOR + "/temperature"
	TOPIC_BACKDOOR_LOCK          string = TOPIC_R3 + CLIENTID_BACKDOOR + "/lock"
	TOPIC_BACKDOOR_AJAR          string = TOPIC_R3 + CLIENTID_BACKDOOR + "/ajar"
	TOPIC_BACKDOOR_GASALERT      string = TOPIC_R3 + CLIENTID_BACKDOOR + "/gasalert"
	TOPIC_BACKDOOR_POWERLOSS     string = TOPIC_R3 + CLIENTID_BACKDOOR + "/powerloss"
	TOPIC_META_PRESENCE          string = TOPIC_R3 + CLIENTID_META + "/presence"
	TOPIC_META_SENSORLOST        string = TOPIC_R3 + CLIENTID_META + "/sensorlost"
	TOPIC_META_REALMOVE          string = TOPIC_R3 + CLIENTID_META + "/realmovement"
	TOPIC_META_TEMPSPIKE         string = TOPIC_R3 + CLIENTID_META + "/TempSensorSpike"
	TOPIC_META_DUSTSPIKE         string = TOPIC_R3 + CLIENTID_META + "/DustSensorSpike"
	TOPIC_GW_DHCPACK             string = TOPIC_R3 + CLIENTID_GW + "/NetDHCPACK"
	TOPIC_GW_STATS               string = TOPIC_R3 + CLIENTID_GW + "/NetGWStatUpdate"
	TOPIC_LASER_CARD             string = TOPIC_R3 + CLIENTID_LASERCUTTER + "/cardpresent"
	ACT_RF433_SEND               string = TOPIC_ACTIONS + ACTDESTID_RF433 + "/sendcode3byte"
	ACT_RF433_SETDELAY           string = TOPIC_ACTIONS + ACTDESTID_RF433 + "/setdelay"
	ACT_YAMAHA_SEND              string = TOPIC_ACTIONS + ACTDESTID_YAMAHA + "/ircmd"
)
