## Use with esp8266 based H801 (controls 5 low-side mosfets for 5V-24V RGB-WW-CW led strips)
##
## in this case it controls two lights:
## - a single-colour WW LED strip mounted around the window, simulating daylight
## - as well as a RGB+W LED strip mounted below the desk
##   - which also implements a random-colour effect
#===============================================================================
substitutions:
  device_name: lothr_ceiling5
  light_name: ceiling5
#===============================================================================

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret realstuffwifi_name
  password: !secret realstuffwifi_pass


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Hotspot"
    password: !secret fallbackwifi_r3_pass

  manual_ip:
    static_ip: 192.168.33.25
    gateway: 192.168.33.1
    dns1: 192.168.33.1
    subnet: 255.255.255.0

# Disable logging, which may help with reboots
logger:
  level: NONE

#Enable Home Assistant API
api:
 encryption:
   key: !secret r3_api_encryption_psk
 reboot_timeout: 3h

ota:
  password: !secret r3_ota_password

mqtt:
    broker: !secret realraum_mqtt_broker

<<: !include r3_include_deckenlichter_ceilinglight.yaml
